language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

env:
  global:
    - secure: "NSDQD+A45WunP4RejhxNWbD+9xhYv4wGu5Qvx3PPLLjBRp1C0sv6bMYcN7f/YRwaqFrZSnYeoURAM3SAYH6oWw5AmVCh76psgx34QPkG+o2whnSmYgzm9Pyj853xF3nwfkMfKgs29Djle/h4tzRo8ppzm6KGNCXddq1KfUfBOtnvcszuUq5tC+9GFgTSIcgqjqS1Q4TXPH7xR83wSjhG78YBloyYZLxwQc72GX5fBdEzP2NWjB9MA+ftAKrFi14Ph+Zg1Hgl22XEnyFF/fj+aFdZx3w0Bcvy3DQ8caCIV17iLeVEQy1YNNaBKjLiyVd35sgu4Yw3RS5rIewfR1wqu8jKC4ZWgT++CzVXovyeE8rrmPNGMbEQUf+19/1wlOBjO1ALtUsa/VjOVc/UlvKG8Kf0+mK20xX4gCYh0YDnq20os/4MQGETwWVEhki3qwO0l35/DPbcAtxaFvm1mcXtEKf/vMU6esIzaDqJm2kX6FxhIt2Q7t1nWWfyqcPQQrwN90HhuEY7nzc6oaNfLrwzNy7jYWC0YrK21QiQPnxJta7OicGgQKmoWKMC+T0VjwA0dWsjWTgU8DA4rqGJTSq30PVHk6YnFURi8LyK7Z/w1BxtKSrrcI9LOReyXLWV3kNtzywPfqW+DMSsrKOdG6j7R9271ZNEuPN+HEnCtM4UOrM="

matrix:
  include:
    - env: MPPP_BUILD="DebugARM64"
      os: linux
      arch: arm64
      dist: bionic
      addons:
        apt:
          packages:
          - build-essential
    - env: MPPP_BUILD="ReleaseGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-4.8
    - env: MPPP_BUILD="DebugGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-4.8
    - env: MPPP_BUILD="Coverage32GCC6"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-multilib
          - g++-multilib
          - gcc-6
          - gcc-6-multilib
          - g++-6
          - g++-6-multilib
          - cmake
    - env: MPPP_BUILD="Documentation"
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - texlive
          - texlive-latex-extra
          - texlive-xetex
          - lmodern
          - latexmk
    - env: MPPP_BUILD="OSXDebug"
      os: osx
      osx_image: xcode6.4
script:
    - mkdir build
    - cd build
    # NOTE: currently, travis does not stop automatically if one of these
    # 2 scripts returns an error code. Thus, we run them together as a single
    # command, so that if install_deps.sh fails the whole build fails immediately
    # rather than executing install_travis.sh as well. See
    # https://github.com/travis-ci/travis-ci/issues/1066
    - ../tools/install_deps.sh && ../tools/install_travis.sh

notifications:
  email: false
